In [9]:
 # Import libraries
 import pandas as pd
 import numpy as np
 from sklearn.linear_model import LinearRegression


### Import your data

In [10]:
df = pd.read_csv("Salary_data1.csv")
df.head()

age  distance  YearsExperience  Salary
0  31.1     77.75              1.1   39343
1  31.3     78.25              1.3   46205
2  31.5     78.75              1.5   37731
3  32.0     80.00              2.0   43525
4  32.2     80.50              2.2   39891

In [11]:
#Seperat the feaurte(Input)

In [12]:
x=df[["age","distance","YearsExperience"]]
y =df[["Salary"]]



In [13]:
# Create and fit the model
model = LinearRegression().fit(x, y)
model

LinearRegression()

In [14]:
# Find th cofecient
model.coef_

array([[-2.68055892e+15,  1.06092560e+15,  2.82449143e+13]])

In [15]:
# ind the intersept
model.intercept_

array([8.4734743e+14])

In [16]:
# predict the model
model.predict([[31.1,77.75,1.1]])

C:\Users\mian\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[36217.125]])

In [17]:
from statistics import linear_regression


reg = linear_regression().fit(x_test,Y_test)
print("TestScore = ", reg.score(x.test,y_test))
print("Train score = ",reg.score(x_train , y_train))

TypeError: linear_regression() missing 2 required positional arguments: 'x' and 'y'